export const styles = {
  content: 'bg-background/90 backdrop-blur-2xl border border-white/15 shadow-[0_24px_72px_rgba(0,0,0,0.85)] max-w-md overflow-hidden',
  header: 'pb-2 border-b border-white/10',
  headerRow: 'flex items-center gap-2',
  iconWrap: 'h-9 w-9 rounded-xl bg-purple-500/20 border border-purple-500/30 flex items-center justify-center text-purple-400',
  icon: 'h-5 w-5',
  title: 'text-xl font-bold',
  description: 'text-xs text-muted-foreground',
  grid: 'grid grid-cols-2 gap-3 py-4',
  monsterButton: 'flex flex-col items-center p-3 rounded-xl border transition-all duration-200',
  monsterButtonEnabled: 'border-white/10 bg-black/40 hover:border-purple-500/40 hover:bg-purple-500/10 hover:scale-105',
  monsterButtonDisabled: 'opacity-40 border-white/5 bg-black/20 cursor-not-allowed',
  spriteWrap: 'relative h-14 w-14 flex items-center justify-center mb-1',
  sprite: 'object-contain drop-shadow',
  name: 'text-xs font-bold capitalize text-foreground text-center',
  powerLabel: 'text-[11px] font-semibold text-purple-400 mt-0.5',
  footer: 'pt-2 border-t border-white/10',
  closeButton: 'border-white/10 text-xs',
} as const;
