import { cva } from 'class-variance-authority';

export const styles = {
  content: 'bg-background/90 backdrop-blur-2xl border border-white/15 shadow-[0_24px_72px_rgba(0,0,0,0.85)] max-w-md overflow-hidden',
  header: 'pb-2 border-b border-white/10',
  headerIcon: 'h-9 w-9 rounded-xl bg-red-500/20 border border-red-500/30 flex items-center justify-center text-red-400',
  headerIconSvg: 'h-5 w-5',
  title: 'text-xl font-bold',
  description: 'text-xs text-muted-foreground',
  descriptionHighlight: 'font-semibold text-foreground',
  tacticalCardBlock: 'rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 space-y-2',
  tacticalCardLabel: 'flex items-center gap-1.5 text-xs font-bold text-amber-400 uppercase tracking-wider',
  tacticalCardLabelIcon: 'h-3.5 w-3.5',
  radioGroup: 'space-y-1.5',
  radioGroupItemDefault: 'flex items-center space-x-2 p-1.5 rounded-lg hover:bg-white/5 transition-colors',
  radioGroupItemOvercome: 'flex items-center space-x-2 p-1.5 rounded-lg bg-yellow-500/15 border border-yellow-400/30',
  radioGroupItemWarChief: 'flex items-center space-x-2 p-1.5 rounded-lg bg-red-500/15 border border-red-400/30',
  radioGroupLabel: 'cursor-pointer text-xs font-medium',
  radioGroupLabelSpecial: 'cursor-pointer text-xs font-semibold',
  radioGroupLabelOvercome: 'text-yellow-300',
  radioGroupLabelWarChief: 'text-red-300',
  combatantsArena: 'flex items-center justify-between gap-2 py-3',
  combatantBox: cva('flex-1 flex flex-col items-center p-3 rounded-xl border transition-all', {
    variants: {
      isWinner: {
        true: 'border-amber-400 bg-amber-500/15 shadow-[0_0_20px_rgba(245,158,11,0.3)]',
        false: 'border-white/10 bg-black/40',
      },
    },
  }),
  combatantName: 'text-xs font-bold truncate max-w-[100px]',
  spriteContainer: 'my-2 h-14 w-14 flex items-center justify-center',
  spriteImage: 'object-contain',
  diceContainer: 'flex flex-wrap justify-center gap-1.5 mt-1',
  diceCell: cva('flex h-9 w-9 items-center justify-center rounded-lg border-2 text-base font-black shadow-md transition-transform duration-300', {
    variants: {
      isWinner: {
        true: 'bg-amber-500/20 border-amber-400 text-amber-300 shadow-[0_0_12px_rgba(245,158,11,0.5)] scale-105',
        false: 'bg-black/60 border-white/20 text-foreground',
      },
    },
  }),
  diceTotal: 'mt-1 text-sm font-black font-mono',
  vsBox: 'flex flex-col items-center shrink-0',
  vsIcon: 'h-8 w-8 rounded-full bg-red-500/20 border border-red-500/40 flex items-center justify-center',
  vsIconSvg: 'h-4 w-4',
  vsLabel: 'text-[10px] font-black uppercase tracking-wider text-muted-foreground mt-0.5',
  outcomeBanner: 'text-center py-2 px-3 rounded-xl bg-black/50 border border-white/10',
  outcomeBannerContent: 'flex items-center justify-center gap-1.5',
  trophyIcon: 'h-5 w-5 text-yellow-400',
  victoryText: 'text-base font-extrabold',
  skullIcon: 'h-5 w-5 text-muted-foreground',
  drawText: 'text-base font-bold text-muted-foreground',
  footer: 'pt-2 border-t border-white/10 gap-2',
  rollButton: 'w-full font-bold bg-gradient-to-r from-red-600 to-amber-600 hover:from-red-500 hover:to-amber-500 text-white shadow-[0_0_16px_rgba(239,68,68,0.4)]',
  confirmButton: 'w-full font-bold bg-gradient-to-r from-amber-500 to-yellow-500 hover:from-amber-400 hover:to-yellow-400 text-black shadow-[0_0_16px_rgba(245,158,11,0.3)]',
  waitingText: 'flex items-center justify-center w-full gap-2 text-xs text-muted-foreground',
  loaderIcon: 'h-4 w-4 animate-spin',
  dicesIcon: 'mr-2 h-4 w-4',
} as const;
