export const styles = {
  card: 'bg-background/40 backdrop-blur-xl border-white/10 shadow-[0_8px_32px_rgba(0,0,0,0.5)]',
  header: 'p-3 pb-1 flex items-center justify-between gap-2',
  title: 'text-xs font-bold uppercase tracking-wider text-muted-foreground whitespace-nowrap',
  toggleRow: 'flex items-center gap-1.5 shrink-0',
  toggleLabel: 'text-[10px] font-medium text-muted-foreground whitespace-nowrap',
  content: 'p-3 pt-0',
  scrollArea: 'h-32 sm:h-36 w-full',
  entriesContainer: 'space-y-1.5 pr-2',
  entry: 'text-xs text-muted-foreground leading-relaxed flex items-start gap-1.5',
  entryIcon: 'h-3 w-3 mt-0.5 shrink-0 text-muted-foreground',
  milestoneIcon: 'h-3 w-3 mt-0.5 shrink-0 text-yellow-400',
  entryText: 'flex-1',
  divider: 'flex items-center gap-2 pt-2 pb-0.5 text-[10px] font-bold uppercase tracking-wider text-muted-foreground/70',
  dividerLine: 'h-px flex-1 bg-white/10',
} as const;
