export const styles = {
  root: 'relative min-h-screen w-full flex items-center justify-center p-3 sm:p-6 lg:p-8 overflow-x-hidden',
  card: 'w-full max-w-6xl bg-background/55 backdrop-blur-2xl border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.8)] relative z-10 overflow-hidden',
  header: 'p-4 sm:p-6 pb-4 border-b border-white/10',
  headerContent: 'flex flex-col sm:flex-row w-full items-start sm:items-center justify-between gap-4',
  headerLeft: 'flex items-center gap-3',
  headerIcon: 'h-11 w-11 rounded-xl bg-gradient-to-br from-amber-500/20 to-primary/20 border border-amber-500/30 flex items-center justify-center text-primary shadow-inner',
  headerCompass: 'h-6 w-6 text-amber-400 animate-spin [animation-duration:25s]',
  headerTextGroup: '',
  headerTitleContainer: 'flex items-center gap-2',
  headerTitle: 'text-2xl sm:text-3xl font-black tracking-wide bg-gradient-to-r from-amber-300 via-yellow-400 to-primary bg-clip-text text-transparent',
  headerBadge: 'bg-black/40 border-amber-400/30 text-amber-300 text-xs hidden sm:inline-flex items-center gap-1 font-bold',
  headerDescription: 'text-xs sm:text-sm text-muted-foreground mt-0.5',
  headerRight: 'flex items-center gap-3 self-end sm:self-center',
  playerInfo: 'text-right',
  playerLabel: 'text-xs text-muted-foreground block',
  playerGreeting: 'text-sm font-bold text-foreground',
  logoutButton: 'text-xs text-muted-foreground hover:text-destructive hover:bg-destructive/10 border border-white/5',
  content: 'p-4 sm:p-6 grid grid-cols-1 lg:grid-cols-12 gap-6',
  leftColumn: 'lg:col-span-4 flex flex-col gap-4',
  createHero: 'rounded-2xl bg-gradient-to-br from-amber-500/10 via-primary/5 to-black/40 border border-amber-500/20 p-4 sm:p-5 flex flex-col gap-3 shadow-lg',
  createHeroHeader: 'flex items-center justify-between',
  createHeroLabel: 'text-xs font-bold uppercase tracking-wider text-amber-400',
  createHeroBadge: 'bg-amber-500/20 text-amber-300 border border-amber-500/30 text-xs',
  createHeroDescription: 'text-xs text-muted-foreground leading-relaxed',
  createButton: 'w-full font-bold bg-gradient-to-r from-amber-500 to-yellow-500 hover:from-amber-400 hover:to-yellow-400 text-black shadow-[0_0_24px_rgba(245,158,11,0.4)] transition-all duration-300 hover:scale-[1.02] py-5 text-sm',
  tacticalGuide: 'rounded-2xl bg-black/30 border border-white/10 p-4 sm:p-5 flex flex-col gap-3',
  tacticalHeader: 'flex items-center gap-2 text-foreground font-bold text-sm',
  tacticalHeaderIcon: 'h-4 w-4 text-cyan-400',
  tacticalContent: 'space-y-2.5 text-xs text-muted-foreground',
  tacticalItem: 'flex items-start gap-2',
  tacticalItemIcon: 'h-4 w-4 shrink-0 mt-0.5',
  rightColumn: 'lg:col-span-8 flex flex-col gap-3',
  roomsHeader: 'flex items-center justify-between px-1',
  roomsHeaderLeft: 'flex items-center gap-2',
  roomsTitle: 'text-sm font-bold uppercase tracking-wider text-foreground',
  roomsCountBadge: 'bg-primary/20 text-primary border border-primary/30 text-xs font-semibold',
  roomsHint: 'text-xs text-muted-foreground hidden sm:inline',
  gamesList: 'max-h-[52vh] overflow-y-auto pr-1 space-y-3 custom-scrollbar',
  loadingState: 'flex flex-col items-center justify-center py-16 gap-3 text-muted-foreground bg-black/20 rounded-2xl border border-white/5',
  emptyState: 'py-16 text-center text-muted-foreground bg-black/20 rounded-2xl border border-white/5 p-6 flex flex-col items-center justify-center gap-2',
  emptyIcon: 'h-10 w-10 text-muted-foreground/40 mb-1',
  emptyTitle: 'font-bold text-foreground text-sm',
  emptyDescription: 'text-xs text-muted-foreground max-w-sm',
} as const;
