export const styles = {
  dialogContent: 'bg-background/90 backdrop-blur-2xl border border-white/15 shadow-[0_24px_72px_rgba(0,0,0,0.85)] max-w-lg overflow-hidden',
  dialogHeader: 'pb-2 border-b border-white/10',
  headerContainer: 'flex items-center gap-2',
  headerIcon: 'h-9 w-9 rounded-xl bg-amber-500/20 border border-amber-500/30 flex items-center justify-center text-amber-400',
  headerTextGroup: '',
  dialogTitle: 'text-xl font-bold',
  dialogDescription: 'text-xs text-muted-foreground',
  formContent: 'grid gap-4 py-3',
  formGroup: 'space-y-1.5',
  label: 'text-xs font-semibold text-foreground',
  input: 'bg-black/40 border-white/10 focus-visible:ring-amber-400',
  selectTrigger: 'bg-black/40 border-white/10',
  selectContent: 'bg-background/95 backdrop-blur-xl border-white/15',
  factionGrid: 'grid grid-cols-2 sm:grid-cols-4 gap-2',
  factionButton: 'flex flex-col items-center justify-center p-2 rounded-xl border transition-all duration-200',
  factionButtonSelected: 'border-amber-400 bg-amber-500/20 shadow-[0_0_15px_rgba(245,158,11,0.4)] scale-105',
  factionButtonUnselected: 'border-white/10 bg-black/30 hover:border-white/20 hover:bg-black/50',
  factionImage: 'object-contain drop-shadow',
  factionName: 'text-[11px] font-bold mt-1 capitalize text-foreground',
  debugModeContainer: 'flex items-center justify-between p-3 rounded-xl bg-black/30 border border-white/10',
  debugModeLabel: 'text-xs font-semibold text-foreground flex items-center gap-1',
  debugModeDescription: 'text-[11px] text-muted-foreground',
  dialogFooter: 'sm:justify-between pt-2 border-t border-white/10 gap-2',
  advancedButton: 'border-white/10 hover:bg-white/5 text-xs',
  createButton: 'font-bold bg-gradient-to-r from-amber-500 to-yellow-500 hover:from-amber-400 hover:to-yellow-400 text-black shadow-[0_0_16px_rgba(245,158,11,0.3)] text-xs px-4',
  helpIcon: 'h-3.5 w-3.5 text-muted-foreground',
} as const;
