export const styles = {
  content: 'bg-background/95 backdrop-blur-2xl border border-white/15 shadow-[0_24px_72px_rgba(0,0,0,0.85)] max-w-md overflow-hidden',
  header: 'pb-2 border-b border-white/10',
  headerRow: 'flex items-center gap-2',
  iconWrap: 'h-9 w-9 rounded-xl bg-purple-500/20 border border-purple-500/30 flex items-center justify-center text-purple-400',
  icon: 'h-5 w-5',
  title: 'text-xl font-bold',
  description: 'text-xs text-muted-foreground',
  footer: 'pt-2 border-t border-white/10',
  footerWithGap: 'pt-2 border-t border-white/10 gap-2',
  closeButton: 'border-white/10 text-xs',

  playerGrid: 'grid grid-cols-2 sm:grid-cols-3 gap-2.5 py-4',
  playerButtonBase: 'flex flex-col items-center p-3 rounded-xl border transition-all duration-200',
  playerButtonSelected: 'border-purple-400 bg-purple-500/20 shadow-[0_0_16px_rgba(168,85,247,0.4)] scale-105',
  playerButtonIdle: 'border-white/10 bg-black/40 hover:border-white/20 hover:bg-black/60',
  spriteWrap: 'relative h-10 w-10 mb-1 flex items-center justify-center',
  sprite: 'object-contain drop-shadow',
  playerName: 'text-xs font-bold truncate max-w-full text-foreground',
  totalResources: 'text-[10px] text-muted-foreground mt-0.5',

  resourceGrid: 'grid grid-cols-3 gap-3 py-4',
  resourceButtonBase: 'relative flex flex-col items-center justify-center p-3 rounded-xl border transition-all duration-200',
  resourceButtonUnavailable: 'opacity-40 border-white/5 bg-black/20 cursor-not-allowed',
  resourceButtonSelected: 'border-purple-400 bg-purple-500/20 shadow-[0_0_16px_rgba(168,85,247,0.4)] scale-105',
  resourceButtonIdle: 'border-white/10 bg-black/40 hover:border-white/20 hover:bg-black/60',
  selectedBadge: 'absolute top-1.5 right-1.5 h-4 w-4 rounded-full bg-purple-500 text-white flex items-center justify-center',
  selectedBadgeIcon: 'h-3 w-3 stroke-[3]',
  resourceSpriteWrap: 'relative w-11 h-11 mb-1 flex items-center justify-center drop-shadow',
  resourceSprite: 'h-full w-full object-contain',
  resourceRow: 'flex items-center gap-1',
  resourceIcon: 'w-3.5 h-3.5',
  resourceName: 'text-xs font-bold capitalize text-foreground',
  availableLabel: 'text-[10px] text-muted-foreground font-mono mt-0.5',
  backButton: 'border-white/10 text-xs',
  backIcon: 'mr-1 h-3.5 w-3.5',
  stealButton:
    'font-bold bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white shadow-[0_0_16px_rgba(168,85,247,0.4)] text-xs px-4',
} as const;
