export const styles = {
  content: 'bg-background/90 backdrop-blur-2xl border border-white/15 shadow-[0_24px_72px_rgba(0,0,0,0.85)] max-w-md overflow-hidden',
  header: 'pb-2 border-b border-white/10',
  headerRow: 'flex items-center gap-2',
  iconWrap: 'h-9 w-9 rounded-xl bg-primary/20 border border-primary/30 flex items-center justify-center text-primary',
  icon: 'h-5 w-5',
  title: 'text-xl font-bold',
  description: 'text-xs text-muted-foreground',
  grid: 'grid grid-cols-2 sm:grid-cols-3 gap-2.5 py-4',
  armyButton: 'flex flex-col items-center p-3 rounded-xl border transition-all duration-200',
  armyButtonSelected: 'border-amber-400 bg-amber-500/20 shadow-[0_0_16px_rgba(245,158,11,0.4)] scale-105',
  armyButtonSelectable: 'border-white/10 bg-black/40 hover:border-white/20 hover:bg-black/60 hover:scale-[1.02]',
  armyButtonDisabled: 'opacity-40 border-white/5 bg-black/20 cursor-not-allowed',
  spriteWrap: 'relative h-12 w-12 flex items-center justify-center mb-1',
  sprite: 'object-contain drop-shadow',
  nameRow: 'flex items-center gap-1',
  name: 'text-xs font-bold text-foreground',
  activeBadge: 'bg-amber-500 text-black text-[9px] px-1 py-0 font-black',
  statusRow: 'flex items-center gap-1 text-[11px] font-semibold mt-1',
  statusIcon: 'h-3.5 w-3.5',
  statusColor: {
    acted: 'text-muted-foreground',
    positioned: 'text-cyan-400',
    ready: 'text-emerald-400',
  },
  footer: 'pt-2 border-t border-white/10',
  closeButton: 'border-white/10 text-xs',
} as const;
