
export enum GameAction {
  Deploy = 'deploy',
  Collect = 'collect',
  Move = 'move',
  Attack = 'attack',
  Position = 'position',
  BuyCard = 'buy-card',
  Upgrade = 'upgrade',
  OpenAbilitiesShop = 'open-abilities-shop',
  CloseAbilitiesShop = 'close-abilities-shop',
  ShowCards = 'show-cards',
  CloseCards = 'close-cards',
  UseCard = 'use-card',
  ConfirmUseCard = 'confirm-use-card',
  EndTurn = 'end-turn',
  Teleport = 'teleport',
  BuyAbility = 'buy-ability',
  CancelAction = 'cancel-action',
  DeselectArmy = 'deselect-army',
  TileClick = 'tile-click',
  SelectResourcePosition = 'select-resource-position',
  ConfirmCollection = 'confirm-collection',
  SelectArmy = 'select-army',
  SelectDefender = 'select-defender',
  CombatRoll = 'combat-roll',
  CloseCombat = 'close-combat',
  CloseCombatViewer = 'close-combat-viewer',
  MonsterCombatRoll = 'monster-combat-roll',
  CloseMonsterCombat = 'close-monster-combat',
  CloseMonsterCombatViewer = 'close-monster-combat-viewer',
  StealResource = 'steal-resource',
  SabotagePlayer = 'sabotage-player',
  GainWealth = 'gain-wealth',
}
