export const styles = {
  content: 'flex w-full flex-col sm:max-w-lg',
  header: '',
  title: '',
  description: '',
  scrollContainer: 'flex-1',
  scrollArea: 'h-full pr-6',
  tabsList: 'grid w-full grid-cols-3',
  tabsContent: 'pt-4 space-y-6',
  fogSection: 'flex items-center justify-between rounded-lg border p-3 shadow-sm',
  fogLabel: '',
  fogDescription: 'text-xs text-muted-foreground',
  sliderGroup: 'space-y-3',
  sliderHeader: 'flex justify-between',
  sliderLabel: '',
  sliderValue: 'font-bold text-primary',
  sliderTrack: 'w-full',
  cardSection: 'space-y-4',
  cardSubheader: 'space-y-1',
  cardTitle: 'font-medium',
  cardDescription: 'text-sm text-muted-foreground',
  cardGrid: 'grid grid-cols-2 gap-4',
  checkboxItem: 'flex items-center space-x-2',
  footer: '',
  footerButtons: 'flex gap-2 justify-end',
} as const;
