export const styles = {
  root: 'flex flex-wrap items-center justify-between gap-x-4 gap-y-2 rounded-lg border border-white/5 bg-black/20 p-3 transition-all duration-300 hover:bg-black/40 hover:scale-[1.02] hover:shadow-[0_0_20px_rgba(0,0,0,0.5)] hover:border-white/20 sm:p-4',
  playersGroup: 'flex flex-1 items-center gap-4 min-w-[200px]',
  avatarStack: 'flex -space-x-2',
  gameName: 'font-bold truncate',
  infoGroup: 'flex items-center gap-4 text-sm text-muted-foreground',
  hostInfo: 'flex items-center gap-1.5',
  playersInfo: 'flex items-center gap-1.5',
  actionsGroup: 'flex items-center gap-2',
  settingsPopoverContent: 'w-80',
  settingsScrollArea: 'h-96 pr-4',
  settingsTitle: 'font-bold text-lg',
  settingsLabel: 'text-sm text-muted-foreground',
  settingsRow: 'flex justify-between items-center text-sm',
  settingsLabel2: 'text-muted-foreground',
  settingsValue: 'font-bold',
  settingsCardsSection: 'space-y-2',
  settingsCardTitle: 'mb-2 text-sm font-medium text-muted-foreground',
  settingsCardBadges: 'flex flex-wrap gap-1',
} as const;
