export const styles = {
  content: 'bg-background/95 backdrop-blur-2xl border border-white/15 shadow-[0_24px_72px_rgba(0,0,0,0.85)] max-w-md overflow-hidden',
  header: 'pb-2 border-b border-white/10',
  headerRow: 'flex items-center gap-2',
  iconWrap: 'h-9 w-9 rounded-xl bg-cyan-500/20 border border-cyan-500/30 flex items-center justify-center text-cyan-400',
  icon: 'h-5 w-5',
  title: 'text-xl font-bold',
  description: 'text-xs text-muted-foreground',
  grid: 'grid grid-cols-2 sm:grid-cols-3 gap-3 py-4',
  option: 'group relative flex flex-col items-center justify-center p-3.5 rounded-xl border border-white/10 bg-black/40 hover:border-cyan-400 hover:bg-cyan-500/15 hover:scale-105 transition-all duration-200',
  spriteWrap: 'relative w-12 h-12 mb-1 drop-shadow flex items-center justify-center',
  sprite: 'h-full w-full object-contain group-hover:scale-110 transition-transform',
  nameRow: 'flex items-center gap-1 mt-1',
  resourceIcon: 'w-4 h-4',
  name: 'text-xs font-bold capitalize text-foreground',
  amount: 'text-xs font-mono font-bold text-cyan-400 mt-0.5',
  footer: 'pt-2 border-t border-white/10',
  closeButton: 'border-white/10 text-xs',
} as const;
